CREATE TABLE if not exists lol.match_ex_info_85 LIKE lol.match_ex_info;
--  INSERT INTO lol.match_ex_info_85 SELECT * FROM lol.match_ex_info WHERE match_id%100=85;
CREATE TABLE if not exists lol.match_ex_info_86 LIKE lol.match_ex_info;
--  INSERT INTO lol.match_ex_info_86 SELECT * FROM lol.match_ex_info WHERE match_id%100=86;
CREATE TABLE if not exists lol.match_ex_info_87 LIKE lol.match_ex_info;
--  INSERT INTO lol.match_ex_info_87 SELECT * FROM lol.match_ex_info WHERE match_id%100=87;
CREATE TABLE if not exists lol.match_ex_info_88 LIKE lol.match_ex_info;
--  INSERT INTO lol.match_ex_info_88 SELECT * FROM lol.match_ex_info WHERE match_id%100=88;
CREATE TABLE if not exists lol.match_ex_info_89 LIKE lol.match_ex_info;
--  INSERT INTO lol.match_ex_info_89 SELECT * FROM lol.match_ex_info WHERE match_id%100=89;
