--  CREATE TABLE if not exists lol.match_ex_info_10 LIKE lol.match_ex_info;
--  INSERT INTO lol.match_ex_info_10 SELECT * FROM lol.match_ex_info WHERE match_id%100=10;
--  CREATE TABLE if not exists lol.match_ex_info_11 LIKE lol.match_ex_info;
--  INSERT INTO lol.match_ex_info_11 SELECT * FROM lol.match_ex_info WHERE match_id%100=11;
--  CREATE TABLE if not exists lol.match_ex_info_12 LIKE lol.match_ex_info;
--  INSERT INTO lol.match_ex_info_12 SELECT * FROM lol.match_ex_info WHERE match_id%100=12;
--  CREATE TABLE if not exists lol.match_ex_info_13 LIKE lol.match_ex_info;
--  INSERT INTO lol.match_ex_info_13 SELECT * FROM lol.match_ex_info WHERE match_id%100=13;
CREATE TABLE if not exists lol.match_ex_info_14 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_14 SELECT * FROM lol.match_ex_info WHERE match_id%100=14;
