--  CREATE TABLE if not exists lol.match_ex_info_35 LIKE lol.match_ex_info;
--  INSERT INTO lol.match_ex_info_35 SELECT * FROM lol.match_ex_info WHERE match_id%100=35;
--  CREATE TABLE if not exists lol.match_ex_info_36 LIKE lol.match_ex_info;
--  INSERT INTO lol.match_ex_info_36 SELECT * FROM lol.match_ex_info WHERE match_id%100=36;
--  CREATE TABLE if not exists lol.match_ex_info_37 LIKE lol.match_ex_info;
--  INSERT INTO lol.match_ex_info_37 SELECT * FROM lol.match_ex_info WHERE match_id%100=37;
--  CREATE TABLE if not exists lol.match_ex_info_38 LIKE lol.match_ex_info;
--  INSERT INTO lol.match_ex_info_38 SELECT * FROM lol.match_ex_info WHERE match_id%100=38;
CREATE TABLE if not exists lol.match_ex_info_39 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_39 SELECT * FROM lol.match_ex_info WHERE match_id%100=39;
