--  CREATE TABLE if not exists lol.match_ex_info_25 LIKE lol.match_ex_info;
--  INSERT INTO lol.match_ex_info_25 SELECT * FROM lol.match_ex_info WHERE match_id%100=25;
--  CREATE TABLE if not exists lol.match_ex_info_26 LIKE lol.match_ex_info;
--  INSERT INTO lol.match_ex_info_26 SELECT * FROM lol.match_ex_info WHERE match_id%100=26;
--  CREATE TABLE if not exists lol.match_ex_info_27 LIKE lol.match_ex_info;
--  INSERT INTO lol.match_ex_info_27 SELECT * FROM lol.match_ex_info WHERE match_id%100=27;
--  CREATE TABLE if not exists lol.match_ex_info_28 LIKE lol.match_ex_info;
--  INSERT INTO lol.match_ex_info_28 SELECT * FROM lol.match_ex_info WHERE match_id%100=28;
CREATE TABLE if not exists lol.match_ex_info_29 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_29 SELECT * FROM lol.match_ex_info WHERE match_id%100=29;
