CREATE TABLE if not exists lol.user_match_list_info_0 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_0 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=0;
CREATE TABLE if not exists lol.user_match_list_info_10 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_10 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=10;
CREATE TABLE if not exists lol.user_match_list_info_20 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_20 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=20;
CREATE TABLE if not exists lol.user_match_list_info_30 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_30 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=30;
CREATE TABLE if not exists lol.user_match_list_info_40 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_40 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=40;
CREATE TABLE if not exists lol.user_match_list_info_50 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_50 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=50;
CREATE TABLE if not exists lol.user_match_list_info_60 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_60 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=60;
CREATE TABLE if not exists lol.user_match_list_info_70 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_70 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=70;
CREATE TABLE if not exists lol.user_match_list_info_80 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_80 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=80;
CREATE TABLE if not exists lol.user_match_list_info_90 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_90 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=90;
