CREATE TABLE if not exists lol.user_match_list_info_1 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_1 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=1;
CREATE TABLE if not exists lol.user_match_list_info_11 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_11 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=11;
CREATE TABLE if not exists lol.user_match_list_info_21 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_21 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=21;
CREATE TABLE if not exists lol.user_match_list_info_31 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_31 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=31;
CREATE TABLE if not exists lol.user_match_list_info_41 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_41 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=41;
CREATE TABLE if not exists lol.user_match_list_info_51 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_51 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=51;
CREATE TABLE if not exists lol.user_match_list_info_61 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_61 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=61;
CREATE TABLE if not exists lol.user_match_list_info_71 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_71 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=71;
CREATE TABLE if not exists lol.user_match_list_info_81 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_81 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=81;
CREATE TABLE if not exists lol.user_match_list_info_91 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_91 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=91;
