CREATE TABLE if not exists lol.user_match_list_info_2 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_2 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=2;
CREATE TABLE if not exists lol.user_match_list_info_12 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_12 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=12;
CREATE TABLE if not exists lol.user_match_list_info_22 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_22 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=22;
CREATE TABLE if not exists lol.user_match_list_info_32 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_32 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=32;
CREATE TABLE if not exists lol.user_match_list_info_42 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_42 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=42;
CREATE TABLE if not exists lol.user_match_list_info_52 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_52 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=52;
CREATE TABLE if not exists lol.user_match_list_info_62 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_62 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=62;
CREATE TABLE if not exists lol.user_match_list_info_72 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_72 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=72;
CREATE TABLE if not exists lol.user_match_list_info_82 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_82 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=82;
CREATE TABLE if not exists lol.user_match_list_info_92 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_92 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=92;
