CREATE TABLE if not exists lol.user_match_list_info_3 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_3 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=3;
CREATE TABLE if not exists lol.user_match_list_info_13 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_13 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=13;
CREATE TABLE if not exists lol.user_match_list_info_23 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_23 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=23;
CREATE TABLE if not exists lol.user_match_list_info_33 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_33 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=33;
CREATE TABLE if not exists lol.user_match_list_info_43 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_43 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=43;
CREATE TABLE if not exists lol.user_match_list_info_53 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_53 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=53;
CREATE TABLE if not exists lol.user_match_list_info_63 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_63 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=63;
CREATE TABLE if not exists lol.user_match_list_info_73 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_73 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=73;
CREATE TABLE if not exists lol.user_match_list_info_83 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_83 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=83;
CREATE TABLE if not exists lol.user_match_list_info_93 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_93 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=93;
