CREATE TABLE if not exists lol.user_match_list_info_4 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_4 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=4;
CREATE TABLE if not exists lol.user_match_list_info_14 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_14 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=14;
CREATE TABLE if not exists lol.user_match_list_info_24 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_24 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=24;
CREATE TABLE if not exists lol.user_match_list_info_34 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_34 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=34;
CREATE TABLE if not exists lol.user_match_list_info_44 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_44 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=44;
CREATE TABLE if not exists lol.user_match_list_info_54 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_54 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=54;
CREATE TABLE if not exists lol.user_match_list_info_64 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_64 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=64;
CREATE TABLE if not exists lol.user_match_list_info_74 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_74 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=74;
CREATE TABLE if not exists lol.user_match_list_info_84 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_84 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=84;
CREATE TABLE if not exists lol.user_match_list_info_94 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_94 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=94;
