CREATE TABLE if not exists lol.user_match_list_info_5 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_5 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=5;
CREATE TABLE if not exists lol.user_match_list_info_15 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_15 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=15;
CREATE TABLE if not exists lol.user_match_list_info_25 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_25 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=25;
CREATE TABLE if not exists lol.user_match_list_info_35 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_35 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=35;
CREATE TABLE if not exists lol.user_match_list_info_45 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_45 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=45;
CREATE TABLE if not exists lol.user_match_list_info_55 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_55 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=55;
CREATE TABLE if not exists lol.user_match_list_info_65 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_65 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=65;
CREATE TABLE if not exists lol.user_match_list_info_75 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_75 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=75;
CREATE TABLE if not exists lol.user_match_list_info_85 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_85 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=85;
CREATE TABLE if not exists lol.user_match_list_info_95 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_95 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=95;
