CREATE TABLE if not exists lol.user_match_list_info_7 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_7 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=7;
CREATE TABLE if not exists lol.user_match_list_info_17 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_17 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=17;
CREATE TABLE if not exists lol.user_match_list_info_27 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_27 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=27;
CREATE TABLE if not exists lol.user_match_list_info_37 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_37 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=37;
CREATE TABLE if not exists lol.user_match_list_info_47 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_47 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=47;
CREATE TABLE if not exists lol.user_match_list_info_57 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_57 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=57;
CREATE TABLE if not exists lol.user_match_list_info_67 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_67 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=67;
CREATE TABLE if not exists lol.user_match_list_info_77 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_77 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=77;
CREATE TABLE if not exists lol.user_match_list_info_87 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_87 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=87;
CREATE TABLE if not exists lol.user_match_list_info_97 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_97 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=97;
