CREATE TABLE if not exists lol.user_match_list_info_8 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_8 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=8;
CREATE TABLE if not exists lol.user_match_list_info_18 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_18 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=18;
CREATE TABLE if not exists lol.user_match_list_info_28 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_28 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=28;
CREATE TABLE if not exists lol.user_match_list_info_38 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_38 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=38;
CREATE TABLE if not exists lol.user_match_list_info_48 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_48 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=48;
CREATE TABLE if not exists lol.user_match_list_info_58 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_58 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=58;
CREATE TABLE if not exists lol.user_match_list_info_68 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_68 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=68;
CREATE TABLE if not exists lol.user_match_list_info_78 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_78 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=78;
CREATE TABLE if not exists lol.user_match_list_info_88 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_88 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=88;
CREATE TABLE if not exists lol.user_match_list_info_98 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_98 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=98;
