CREATE TABLE if not exists lol.user_match_list_info_9 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_9 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=9;
CREATE TABLE if not exists lol.user_match_list_info_19 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_19 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=19;
CREATE TABLE if not exists lol.user_match_list_info_29 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_29 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=29;
CREATE TABLE if not exists lol.user_match_list_info_39 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_39 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=39;
CREATE TABLE if not exists lol.user_match_list_info_49 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_49 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=49;
CREATE TABLE if not exists lol.user_match_list_info_59 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_59 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=59;
CREATE TABLE if not exists lol.user_match_list_info_69 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_69 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=69;
CREATE TABLE if not exists lol.user_match_list_info_79 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_79 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=79;
CREATE TABLE if not exists lol.user_match_list_info_89 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_89 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=89;
CREATE TABLE if not exists lol.user_match_list_info_99 LIKE lol.user_match_list_info;
INSERT INTO lol.user_match_list_info_99 SELECT * FROM lol.user_match_list_info WHERE crc32(user_id_name)%100=99;
