CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_0 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_0 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_1 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_1 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_2 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_2 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_3 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_3 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_4 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_4 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_5 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_5 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_6 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_6 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_7 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_7 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_8 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_8 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_9 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_9 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_10 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_10 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_11 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_11 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_12 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_12 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_13 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_13 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_14 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_14 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_15 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_15 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_16 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_16 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_17 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_17 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_18 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_18 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_19 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_19 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_20 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_20 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_21 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_21 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_22 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_22 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_23 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_23 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_24 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_24 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_25 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_25 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_26 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_26 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_27 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_27 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_28 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_28 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_29 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_29 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_30 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_30 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_31 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_31 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_32 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_32 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_33 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_33 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_34 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_34 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_35 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_35 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_36 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_36 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_37 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_37 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_38 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_38 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_39 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_39 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_40 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_40 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_41 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_41 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_42 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_42 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_43 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_43 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_44 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_44 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_45 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_45 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_46 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_46 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_47 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_47 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_48 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_48 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_49 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_49 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_50 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_50 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_51 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_51 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_52 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_52 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_53 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_53 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_54 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_54 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_55 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_55 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_56 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_56 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_57 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_57 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_58 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_58 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_59 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_59 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_60 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_60 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_61 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_61 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_62 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_62 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_63 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_63 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_64 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_64 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_65 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_65 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_66 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_66 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_67 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_67 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_68 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_68 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_69 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_69 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_70 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_70 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_71 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_71 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_72 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_72 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_73 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_73 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_74 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_74 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_75 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_75 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_76 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_76 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_77 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_77 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_78 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_78 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_79 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_79 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_80 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_80 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_81 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_81 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_82 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_82 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_83 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_83 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_84 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_84 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_85 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_85 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_86 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_86 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_87 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_87 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_88 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_88 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_89 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_89 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_90 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_90 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_91 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_91 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_92 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_92 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_93 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_93 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_94 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_94 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_95 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_95 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_96 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_96 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_97 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_97 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_98 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_98 (user_id_name(15));
CREATE INDEX user_id_name_area_id_name_index on lol.user_match_list_info_99 (user_id_name(15), area_id_name(10));
CREATE INDEX user_id_name_index on lol.user_match_list_info_99 (user_id_name(15));
