CREATE TABLE lol.match_ex_info_0 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_0 SELECT * FROM lol.match_ex_info WHERE match_id%100=0;
CREATE TABLE lol.match_ex_info_1 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_1 SELECT * FROM lol.match_ex_info WHERE match_id%100=1;
CREATE TABLE lol.match_ex_info_2 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_2 SELECT * FROM lol.match_ex_info WHERE match_id%100=2;
CREATE TABLE lol.match_ex_info_3 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_3 SELECT * FROM lol.match_ex_info WHERE match_id%100=3;
CREATE TABLE lol.match_ex_info_4 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_4 SELECT * FROM lol.match_ex_info WHERE match_id%100=4;
CREATE TABLE lol.match_ex_info_5 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_5 SELECT * FROM lol.match_ex_info WHERE match_id%100=5;
CREATE TABLE lol.match_ex_info_6 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_6 SELECT * FROM lol.match_ex_info WHERE match_id%100=6;
CREATE TABLE lol.match_ex_info_7 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_7 SELECT * FROM lol.match_ex_info WHERE match_id%100=7;
CREATE TABLE lol.match_ex_info_8 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_8 SELECT * FROM lol.match_ex_info WHERE match_id%100=8;
CREATE TABLE lol.match_ex_info_9 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_9 SELECT * FROM lol.match_ex_info WHERE match_id%100=9;
CREATE TABLE lol.match_ex_info_10 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_10 SELECT * FROM lol.match_ex_info WHERE match_id%100=10;
CREATE TABLE lol.match_ex_info_11 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_11 SELECT * FROM lol.match_ex_info WHERE match_id%100=11;
CREATE TABLE lol.match_ex_info_12 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_12 SELECT * FROM lol.match_ex_info WHERE match_id%100=12;
CREATE TABLE lol.match_ex_info_13 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_13 SELECT * FROM lol.match_ex_info WHERE match_id%100=13;
CREATE TABLE lol.match_ex_info_14 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_14 SELECT * FROM lol.match_ex_info WHERE match_id%100=14;
CREATE TABLE lol.match_ex_info_15 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_15 SELECT * FROM lol.match_ex_info WHERE match_id%100=15;
CREATE TABLE lol.match_ex_info_16 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_16 SELECT * FROM lol.match_ex_info WHERE match_id%100=16;
CREATE TABLE lol.match_ex_info_17 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_17 SELECT * FROM lol.match_ex_info WHERE match_id%100=17;
CREATE TABLE lol.match_ex_info_18 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_18 SELECT * FROM lol.match_ex_info WHERE match_id%100=18;
CREATE TABLE lol.match_ex_info_19 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_19 SELECT * FROM lol.match_ex_info WHERE match_id%100=19;
CREATE TABLE lol.match_ex_info_20 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_20 SELECT * FROM lol.match_ex_info WHERE match_id%100=20;
CREATE TABLE lol.match_ex_info_21 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_21 SELECT * FROM lol.match_ex_info WHERE match_id%100=21;
CREATE TABLE lol.match_ex_info_22 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_22 SELECT * FROM lol.match_ex_info WHERE match_id%100=22;
CREATE TABLE lol.match_ex_info_23 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_23 SELECT * FROM lol.match_ex_info WHERE match_id%100=23;
CREATE TABLE lol.match_ex_info_24 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_24 SELECT * FROM lol.match_ex_info WHERE match_id%100=24;
CREATE TABLE lol.match_ex_info_25 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_25 SELECT * FROM lol.match_ex_info WHERE match_id%100=25;
CREATE TABLE lol.match_ex_info_26 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_26 SELECT * FROM lol.match_ex_info WHERE match_id%100=26;
CREATE TABLE lol.match_ex_info_27 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_27 SELECT * FROM lol.match_ex_info WHERE match_id%100=27;
CREATE TABLE lol.match_ex_info_28 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_28 SELECT * FROM lol.match_ex_info WHERE match_id%100=28;
CREATE TABLE lol.match_ex_info_29 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_29 SELECT * FROM lol.match_ex_info WHERE match_id%100=29;
CREATE TABLE lol.match_ex_info_30 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_30 SELECT * FROM lol.match_ex_info WHERE match_id%100=30;
CREATE TABLE lol.match_ex_info_31 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_31 SELECT * FROM lol.match_ex_info WHERE match_id%100=31;
CREATE TABLE lol.match_ex_info_32 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_32 SELECT * FROM lol.match_ex_info WHERE match_id%100=32;
CREATE TABLE lol.match_ex_info_33 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_33 SELECT * FROM lol.match_ex_info WHERE match_id%100=33;
CREATE TABLE lol.match_ex_info_34 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_34 SELECT * FROM lol.match_ex_info WHERE match_id%100=34;
CREATE TABLE lol.match_ex_info_35 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_35 SELECT * FROM lol.match_ex_info WHERE match_id%100=35;
CREATE TABLE lol.match_ex_info_36 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_36 SELECT * FROM lol.match_ex_info WHERE match_id%100=36;
CREATE TABLE lol.match_ex_info_37 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_37 SELECT * FROM lol.match_ex_info WHERE match_id%100=37;
CREATE TABLE lol.match_ex_info_38 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_38 SELECT * FROM lol.match_ex_info WHERE match_id%100=38;
CREATE TABLE lol.match_ex_info_39 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_39 SELECT * FROM lol.match_ex_info WHERE match_id%100=39;
CREATE TABLE lol.match_ex_info_40 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_40 SELECT * FROM lol.match_ex_info WHERE match_id%100=40;
CREATE TABLE lol.match_ex_info_41 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_41 SELECT * FROM lol.match_ex_info WHERE match_id%100=41;
CREATE TABLE lol.match_ex_info_42 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_42 SELECT * FROM lol.match_ex_info WHERE match_id%100=42;
CREATE TABLE lol.match_ex_info_43 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_43 SELECT * FROM lol.match_ex_info WHERE match_id%100=43;
CREATE TABLE lol.match_ex_info_44 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_44 SELECT * FROM lol.match_ex_info WHERE match_id%100=44;
CREATE TABLE lol.match_ex_info_45 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_45 SELECT * FROM lol.match_ex_info WHERE match_id%100=45;
CREATE TABLE lol.match_ex_info_46 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_46 SELECT * FROM lol.match_ex_info WHERE match_id%100=46;
CREATE TABLE lol.match_ex_info_47 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_47 SELECT * FROM lol.match_ex_info WHERE match_id%100=47;
CREATE TABLE lol.match_ex_info_48 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_48 SELECT * FROM lol.match_ex_info WHERE match_id%100=48;
CREATE TABLE lol.match_ex_info_49 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_49 SELECT * FROM lol.match_ex_info WHERE match_id%100=49;
CREATE TABLE lol.match_ex_info_50 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_50 SELECT * FROM lol.match_ex_info WHERE match_id%100=50;
CREATE TABLE lol.match_ex_info_51 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_51 SELECT * FROM lol.match_ex_info WHERE match_id%100=51;
CREATE TABLE lol.match_ex_info_52 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_52 SELECT * FROM lol.match_ex_info WHERE match_id%100=52;
CREATE TABLE lol.match_ex_info_53 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_53 SELECT * FROM lol.match_ex_info WHERE match_id%100=53;
CREATE TABLE lol.match_ex_info_54 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_54 SELECT * FROM lol.match_ex_info WHERE match_id%100=54;
CREATE TABLE lol.match_ex_info_55 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_55 SELECT * FROM lol.match_ex_info WHERE match_id%100=55;
CREATE TABLE lol.match_ex_info_56 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_56 SELECT * FROM lol.match_ex_info WHERE match_id%100=56;
CREATE TABLE lol.match_ex_info_57 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_57 SELECT * FROM lol.match_ex_info WHERE match_id%100=57;
CREATE TABLE lol.match_ex_info_58 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_58 SELECT * FROM lol.match_ex_info WHERE match_id%100=58;
CREATE TABLE lol.match_ex_info_59 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_59 SELECT * FROM lol.match_ex_info WHERE match_id%100=59;
CREATE TABLE lol.match_ex_info_60 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_60 SELECT * FROM lol.match_ex_info WHERE match_id%100=60;
CREATE TABLE lol.match_ex_info_61 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_61 SELECT * FROM lol.match_ex_info WHERE match_id%100=61;
CREATE TABLE lol.match_ex_info_62 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_62 SELECT * FROM lol.match_ex_info WHERE match_id%100=62;
CREATE TABLE lol.match_ex_info_63 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_63 SELECT * FROM lol.match_ex_info WHERE match_id%100=63;
CREATE TABLE lol.match_ex_info_64 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_64 SELECT * FROM lol.match_ex_info WHERE match_id%100=64;
CREATE TABLE lol.match_ex_info_65 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_65 SELECT * FROM lol.match_ex_info WHERE match_id%100=65;
CREATE TABLE lol.match_ex_info_66 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_66 SELECT * FROM lol.match_ex_info WHERE match_id%100=66;
CREATE TABLE lol.match_ex_info_67 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_67 SELECT * FROM lol.match_ex_info WHERE match_id%100=67;
CREATE TABLE lol.match_ex_info_68 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_68 SELECT * FROM lol.match_ex_info WHERE match_id%100=68;
CREATE TABLE lol.match_ex_info_69 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_69 SELECT * FROM lol.match_ex_info WHERE match_id%100=69;
CREATE TABLE lol.match_ex_info_70 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_70 SELECT * FROM lol.match_ex_info WHERE match_id%100=70;
CREATE TABLE lol.match_ex_info_71 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_71 SELECT * FROM lol.match_ex_info WHERE match_id%100=71;
CREATE TABLE lol.match_ex_info_72 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_72 SELECT * FROM lol.match_ex_info WHERE match_id%100=72;
CREATE TABLE lol.match_ex_info_73 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_73 SELECT * FROM lol.match_ex_info WHERE match_id%100=73;
CREATE TABLE lol.match_ex_info_74 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_74 SELECT * FROM lol.match_ex_info WHERE match_id%100=74;
CREATE TABLE lol.match_ex_info_75 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_75 SELECT * FROM lol.match_ex_info WHERE match_id%100=75;
CREATE TABLE lol.match_ex_info_76 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_76 SELECT * FROM lol.match_ex_info WHERE match_id%100=76;
CREATE TABLE lol.match_ex_info_77 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_77 SELECT * FROM lol.match_ex_info WHERE match_id%100=77;
CREATE TABLE lol.match_ex_info_78 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_78 SELECT * FROM lol.match_ex_info WHERE match_id%100=78;
CREATE TABLE lol.match_ex_info_79 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_79 SELECT * FROM lol.match_ex_info WHERE match_id%100=79;
CREATE TABLE lol.match_ex_info_80 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_80 SELECT * FROM lol.match_ex_info WHERE match_id%100=80;
CREATE TABLE lol.match_ex_info_81 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_81 SELECT * FROM lol.match_ex_info WHERE match_id%100=81;
CREATE TABLE lol.match_ex_info_82 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_82 SELECT * FROM lol.match_ex_info WHERE match_id%100=82;
CREATE TABLE lol.match_ex_info_83 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_83 SELECT * FROM lol.match_ex_info WHERE match_id%100=83;
CREATE TABLE lol.match_ex_info_84 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_84 SELECT * FROM lol.match_ex_info WHERE match_id%100=84;
CREATE TABLE lol.match_ex_info_85 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_85 SELECT * FROM lol.match_ex_info WHERE match_id%100=85;
CREATE TABLE lol.match_ex_info_86 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_86 SELECT * FROM lol.match_ex_info WHERE match_id%100=86;
CREATE TABLE lol.match_ex_info_87 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_87 SELECT * FROM lol.match_ex_info WHERE match_id%100=87;
CREATE TABLE lol.match_ex_info_88 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_88 SELECT * FROM lol.match_ex_info WHERE match_id%100=88;
CREATE TABLE lol.match_ex_info_89 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_89 SELECT * FROM lol.match_ex_info WHERE match_id%100=89;
CREATE TABLE lol.match_ex_info_90 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_90 SELECT * FROM lol.match_ex_info WHERE match_id%100=90;
CREATE TABLE lol.match_ex_info_91 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_91 SELECT * FROM lol.match_ex_info WHERE match_id%100=91;
CREATE TABLE lol.match_ex_info_92 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_92 SELECT * FROM lol.match_ex_info WHERE match_id%100=92;
CREATE TABLE lol.match_ex_info_93 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_93 SELECT * FROM lol.match_ex_info WHERE match_id%100=93;
CREATE TABLE lol.match_ex_info_94 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_94 SELECT * FROM lol.match_ex_info WHERE match_id%100=94;
CREATE TABLE lol.match_ex_info_95 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_95 SELECT * FROM lol.match_ex_info WHERE match_id%100=95;
CREATE TABLE lol.match_ex_info_96 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_96 SELECT * FROM lol.match_ex_info WHERE match_id%100=96;
CREATE TABLE lol.match_ex_info_97 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_97 SELECT * FROM lol.match_ex_info WHERE match_id%100=97;
CREATE TABLE lol.match_ex_info_98 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_98 SELECT * FROM lol.match_ex_info WHERE match_id%100=98;
CREATE TABLE lol.match_ex_info_99 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_99 SELECT * FROM lol.match_ex_info WHERE match_id%100=99;
