--  CREATE TABLE if not exists lol.match_ex_info_95 LIKE lol.match_ex_info;
--  INSERT INTO lol.match_ex_info_95 SELECT * FROM lol.match_ex_info WHERE match_id%100=95;
--  CREATE TABLE if not exists lol.match_ex_info_96 LIKE lol.match_ex_info;
--  INSERT INTO lol.match_ex_info_96 SELECT * FROM lol.match_ex_info WHERE match_id%100=96;
--  CREATE TABLE if not exists lol.match_ex_info_97 LIKE lol.match_ex_info;
--  INSERT INTO lol.match_ex_info_97 SELECT * FROM lol.match_ex_info WHERE match_id%100=97;
CREATE TABLE if not exists lol.match_ex_info_98 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_98 SELECT * FROM lol.match_ex_info WHERE match_id%100=98;
CREATE TABLE if not exists lol.match_ex_info_99 LIKE lol.match_ex_info;
INSERT INTO lol.match_ex_info_99 SELECT * FROM lol.match_ex_info WHERE match_id%100=99;
